<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Article extends \App\Entity\Article implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'echangeCrossCat', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'datePublication', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'idGouvernorat', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'idProprietaire', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'idCategorie', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'boost'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'echangeCrossCat', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'datePublication', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'idGouvernorat', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'idProprietaire', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'idCategorie', '' . "\0" . 'App\\Entity\\Article' . "\0" . 'boost'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Article $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEchangeCrossCat(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEchangeCrossCat', []);

        return parent::getEchangeCrossCat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEchangeCrossCat(int $echangeCrossCat): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEchangeCrossCat', [$echangeCrossCat]);

        return parent::setEchangeCrossCat($echangeCrossCat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatePublication(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatePublication', []);

        return parent::getDatePublication();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatePublication(\DateTimeInterface $datePublication): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatePublication', [$datePublication]);

        return parent::setDatePublication($datePublication);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat(string $etat): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre(string $titre): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(string $image): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdGouvernorat(): ?\App\Entity\Gouvernorat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdGouvernorat', []);

        return parent::getIdGouvernorat();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdGouvernorat(?\App\Entity\Gouvernorat $idGouvernorat): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdGouvernorat', [$idGouvernorat]);

        return parent::setIdGouvernorat($idGouvernorat);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProprietaire(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProprietaire', []);

        return parent::getIdProprietaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProprietaire(?\App\Entity\User $idProprietaire): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProprietaire', [$idProprietaire]);

        return parent::setIdProprietaire($idProprietaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCategorie(): ?\App\Entity\CategorieArticle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCategorie', []);

        return parent::getIdCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCategorie(?\App\Entity\CategorieArticle $idCategorie): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCategorie', [$idCategorie]);

        return parent::setIdCategorie($idCategorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoost(): ?\App\Entity\Boost
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoost', []);

        return parent::getBoost();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoost(?\App\Entity\Boost $boost): \App\Entity\Article
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoost', [$boost]);

        return parent::setBoost($boost);
    }

    /**
     * {@inheritDoc}
     */
    public function isLikedByUser(\App\Entity\User $user, $likes): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isLikedByUser', [$user, $likes]);

        return parent::isLikedByUser($user, $likes);
    }

}
