<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGbxCxvO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGbxCxvO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGbxCxvO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGbxCxvO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGbxCxvO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GbxCxvO',
    'container.build_id' => '77e039c1',
    'container.build_time' => 1651886023,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGbxCxvO');
