<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'app_article_contr' => [[], ['_controller' => 'App\\Controller\\ArticleContrController::index'], [], [['text', '/article/contr']], [], []],
    'backoffice' => [[], ['_controller' => 'App\\Controller\\ArticleContrController::backoffice'], [], [['text', '/backoffice']], [], []],
    'article_cont' => [[], ['_controller' => 'App\\Controller\\ArticleContrController::indexAdmin'], [], [['text', '/article_contr']], [], []],
    'postlike' => [['id'], ['_controller' => 'App\\Controller\\ArticleContrController::like'], [], [['variable', '', '[^/]++', 'id'], ['text', '/article_contr/likeadd']], [], []],
    'boosts' => [[], ['_controller' => 'App\\Controller\\BoostContrController::index'], [], [['text', '/']], [], []],
    'boost_contr' => [[], ['_controller' => 'App\\Controller\\BoostContrController::add'], [], [['text', '/boost/add']], [], []],
    'supp_boost' => [['idBoost'], ['_controller' => 'App\\Controller\\BoostContrController::suppressionBoost'], [], [['variable', '/', '[^/]++', 'idBoost'], ['text', '/removeBoost']], [], []],
    'modifBoost' => [['idBoost'], ['_controller' => 'App\\Controller\\BoostContrController::modifBoost'], [], [['variable', '/', '[^/]++', 'idBoost'], ['text', '/modifBoost']], [], []],
    'payement' => [[], ['_controller' => 'App\\Controller\\BoostContrController::payement'], [], [['text', '/payementBoost']], [], []],
    'checkout' => [[], ['_controller' => 'App\\Controller\\BoostContrController::checkout'], [], [['text', '/checkout']], [], []],
    'success-url' => [[], ['_controller' => 'App\\Controller\\BoostContrController::successUrl'], [], [['text', '/success-url']], [], []],
    'cancel-url' => [[], ['_controller' => 'App\\Controller\\BoostContrController::cancelUrl'], [], [['text', '/cancel-url']], [], []],
    'pdfBoost' => [[], ['_controller' => 'App\\Controller\\BoostContrController::pdfAction'], [], [['text', '/pdfBoost']], [], []],
    'app_like_contr' => [[], ['_controller' => 'App\\Controller\\LikeContrController::index'], [], [['text', '/like/contr']], [], []],
];
